application: hr-note
version: gblog-first
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /favicon.ico
  static_files: static/image/favicon.ico
  upload: static/image/favicon.ico

- url: /static/*
  static_dir: static

- url: /.*
  script: blog.app

libraries:
- name: jinja2
  version: latest
- name: webapp2
  version: latest

builtins:
- remote_api: on
