application: hr-note
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: ^/static/.*
  

- url: /.*
  script: blog.app

libraries:
- name: jinja2
  version: latest
- name: webapp2
  version: latest

